spring:
  datasource:
    url: jdbc:mysql://mysql:3306/pokemondb
    username: pokemon
    password: pokemon123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false